---
deployment:
  tasks:
    - export DEPLOYPATH=/home/kita/public_html/thebigfootfinder.com
    - /bin/cp -R dist/css $DEPLOYPATH
    - /bin/cp -R dist/img $DEPLOYPATH
    - /bin/cp -R dist/js $DEPLOYPATH
    - /bin/cp dist/favicon.ico $DEPLOYPATH
    - /bin/cp dist/index.html $DEPLOYPATH
