---
deployment:
  tasks:
    - export DEPLOYPATH=/home/kita/public_html/thebigfootfinder
    - /bin/cp -R css $DEPLOYPATH
    - /bin/cp -R img $DEPLOYPATH
    - /bin/cp -R js $DEPLOYPATH
    - /bin/cp favicon.ico $DEPLOYPATH
    - /bin/cp index.html $DEPLOYPATH
